"""add tags

Revision ID: 1a507d6957e8
Revises: af28f6054e12
Create Date: 2026-06-11 23:23:35.567553

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1a507d6957e8'
down_revision = 'af28f6054e12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('tags', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    op.drop_column('pipeline', 'tags')
    # ### end Alembic commands ###
