"""Adjusts in tasks

Revision ID: 2232f498d42e
Revises: d469ee22a37d
Create Date: 2019-02-13 10:35:29.598613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2232f498d42e'
down_revision = 'd469ee22a37d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('SERVICE', 'PIPELINE', 'TEMPLATE', name='TaskGroupTypeEnumType'), nullable=False),
    sa.Column('color', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('flow', sa.Column('environment', sa.Enum('DESIGN', 'DEPLOYMENT', name='DiagramEnvironmentEnumType'), nullable=False))
    op.add_column('task', sa.Column('environment', sa.Enum('DESIGN', 'DEPLOYMENT', name='DiagramEnvironmentEnumType'), nullable=False))
    op.add_column('workflow', sa.Column('deployment_enabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'deployment_enabled')
    op.drop_column('task', 'environment')
    op.drop_column('flow', 'environment')
    op.drop_table('task_group')
    # ### end Alembic commands ###
