""" operation subset  

Revision ID: 253949e0710b
Revises: 54a6de142d33
Create Date: 2020-05-28 18:13:11.526901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '253949e0710b'
down_revision = '54a6de142d33'
branch_labels = None
depends_on = None


def upgrade():

    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operation_subset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], name='fk_platform_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operation_subset_operation',
    sa.Column('operation_subset_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operation_id'], ['operation.id'], ),
    sa.ForeignKeyConstraint(['operation_subset_id'], ['operation_subset.id'], )
    )
    op.create_table('role_operation_subset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('subset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subset_id'], ['operation_subset.id'], name='fk_operation_subset_id'),
    sa.PrimaryKeyConstraint('id')
    )

    op.add_column('workflow', sa.Column('subset_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_workflow_operation_subset_id', 'workflow', 'operation_subset', ['subset_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_operation_subset')
    op.drop_table('operation_subset_operation')
    op.drop_table('operation_subset')

    op.drop_constraint('fk_workflow_operation_subset_id', 'workflow', type_='foreignkey')
    op.drop_column('workflow', 'subset_id')
    # ### end Alembic commands ###
