"""migration_jan_20

Revision ID: 28359f24766c
Revises: 20f35e630daf
Create Date: 2020-01-22 09:18:25.752499

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '28359f24766c'
down_revision = '20f35e630daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task',
                  sa.Column('display_order', sa.Integer(), nullable=True))
    op.alter_column('task', 'height',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('task', 'width',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True,
                    existing_server_default=sa.text("'0'"))
    op.drop_constraint('fk_task_group_id', 'task', type_='foreignkey')

    op.add_column('workflow', sa.Column('publishing_enabled', sa.Boolean(),
                                        nullable=False,
                                        server_default=sa.text("'0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('fk_task_group_id', 'task', 'task', ['group_id'],
                          ['id'])
    op.alter_column('task', 'width',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.alter_column('task', 'height',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False,
                    existing_server_default=sa.text("'0'"))
    op.drop_column('task', 'display_order')

    op.drop_column('workflow', 'publishing_enabled')
    # ### end Alembic commands ###
