"""Graph entities

Revision ID: 32eebe6744e5
Revises: a7c44fb9bc18
Create Date: 2024-05-20 21:37:44.248263

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32eebe6744e5'
down_revision = 'a7c44fb9bc18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vertice_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('namespace', sa.String(length=200), nullable=True),
    sa.Column('small_icon', sa.String(length=200), nullable=True),
    sa.Column('icon', sa.String(length=200), nullable=True),
    sa.Column('large_icon', sa.String(length=200), nullable=True),
    sa.Column('display_property', sa.String(length=200), nullable=True),
    sa.Column('plural', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['vertice_type.id'], name='fk_vertice_type_parent_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vertice_type_parent_id'), 'vertice_type', ['parent_id'], unique=False)
    op.create_table('vertice_type_property',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('data_type', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('is_main', sa.Boolean(), nullable=False),
    sa.Column('vertice_type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['vertice_type_id'], ['vertice_type.id'], name='fk_vertice_type_property_vertice_type_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vertice_type_property_vertice_type_id'), 'vertice_type_property', ['vertice_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vertice_type_property_vertice_type_id'), table_name='vertice_type_property')
    op.drop_table('vertice_type_property')
    op.drop_index(op.f('ix_vertice_type_parent_id'), table_name='vertice_type')
    op.drop_table('vertice_type')
    # ### end Alembic commands ###
