"""empty message

Revision ID: 35e7de3e6315
Revises: d7b25721d1ff
Create Date: 2017-04-28 15:36:50.295172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '35e7de3e6315'
down_revision = 'd7b25721d1ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow', 'source_port_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('flow', 'target_port_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flow', 'target_port_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('flow', 'source_port_name',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
