"""Changing column 'operation_form_field.default' to allow null

Revision ID: 3baf65d9906d
Revises: f654bbef525d
Create Date: 2017-02-17 13:42:34.838982

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3baf65d9906d'
down_revision = 'f654bbef525d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation_form_field', 'default',
               existing_type=mysql.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('operation_form_field', 'default',
               existing_type=mysql.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
