"""Add field periodicity

Revision ID: 4ab0d91a4dc8
Revises: 6ce4a4ac085f
Create Date: 2024-07-29 09:33:33.435017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ab0d91a4dc8'
down_revision = '6ce4a4ac085f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('periodicity', sa.String(length=2000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'periodicity')
    # ### end Alembic commands ###
