""" workflow publishing field  

Revision ID: 54a6de142d33
Revises: 253949e0710b
Create Date: 2020-06-09 15:22:22.461924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54a6de142d33'
down_revision = '253949e0710b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('publishing_enabled', sa.Boolean(), nullable=False))
    op.add_column('workflow_variable', sa.Column('parameters', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow', 'publishing_enabled')
    op.drop_column('workflow_variable', 'parameters')
    # ### end Alembic commands ###
