"""add lemon tables

Revision ID: 71d4fa301507
Revises: a237518ec5e1
Create Date: 2023-11-27 15:16:00.093155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71d4fa301507'
down_revision = 'a237518ec5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('scheduling', sa.String(length=300), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_template',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('scheduling', sa.String(length=300), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_template_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('pipelinetemplate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipelinetemplate_id'], ['pipeline_template.id'], name='fk_pipeline_template_step_template_pipeline_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_template_step_pipelinetemplate_id'), 'pipeline_template_step', ['pipelinetemplate_id'], unique=False)
    op.create_table('pipeline_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('workflow_type', sa.Enum('WORKFLOW', 'USER_TEMPLATE', 'SYSTEM_TEMPLATE', 'SUB_FLOW', 'DATA_EXPLORER', 'MODEL_BUILDER', 'VIS_BUILDER', name='WorkflowType'), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], name='fk_pipeline_step_pipeline_id'),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], name='fk_pipeline_step_workflow_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_step_pipeline_id'), 'pipeline_step', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_pipeline_step_workflow_id'), 'pipeline_step', ['workflow_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_step_workflow_id'), table_name='pipeline_step')
    op.drop_index(op.f('ix_pipeline_step_pipeline_id'), table_name='pipeline_step')
    op.drop_table('pipeline_step')
    op.drop_index(op.f('ix_pipeline_template_step_pipelinetemplate_id'), table_name='pipeline_template_step')
    op.drop_table('pipeline_template_step')
    op.drop_table('pipeline_template')
    op.drop_table('pipeline')
    # ### end Alembic commands ###
