"""migration_jan_31

Revision ID: 736a6469026d
Revises: 28359f24766c
Create Date: 2020-02-03 10:34:19.895688

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '736a6469026d'
down_revision = '28359f24766c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_variable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', mysql.LONGTEXT(), nullable=True),
    sa.Column('type', sa.Enum('DATETIME', 'INTEGER', 'BINARY', 'TEXT', 'FLOAT', 'TIMESTAMP', 'DATE', 'LAT_LONG', 'FILE', 'TIME', 'CHARACTER', 'DECIMAL', 'ENUM', 'LONG', 'VECTOR', 'DOUBLE', name='DataTypeEnumType'), nullable=False),
    sa.Column('multiplicity', sa.Integer(), nullable=False),
    sa.Column('suggested_widget', sa.String(length=200), nullable=True),
    sa.Column('default_value', mysql.LONGTEXT(), nullable=True),
    sa.Column('workflow_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('fk_task_group_id', table_name='task')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('fk_task_group_id', 'task', ['group_id'], unique=False)
    op.drop_table('workflow_variable')
    # ### end Alembic commands ###
