"""Fixing required fields

Revision ID: 8d2b3386d63f
Revises: 995d4fa1bfd0
Create Date: 2017-05-23 18:23:45.911491

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8d2b3386d63f'
down_revision = '995d4fa1bfd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET foreign_key_checks = 0')
    op.alter_column('operation_operation_form', 'operation_form_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.alter_column('operation_operation_form', 'operation_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.alter_column('operation_platform', 'operation_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.alter_column('operation_platform', 'platform_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.alter_column('operation_port_interface_operation_port',
                    'operation_port_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.alter_column('operation_port_interface_operation_port',
                    'operation_port_interface_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=False)
    op.execute('SET foreign_key_checks = 1')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('SET foreign_key_checks = 0')
    op.alter_column('operation_port_interface_operation_port',
                    'operation_port_interface_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.alter_column('operation_port_interface_operation_port',
                    'operation_port_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.alter_column('operation_platform', 'platform_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.alter_column('operation_platform', 'operation_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.alter_column('operation_operation_form', 'operation_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.alter_column('operation_operation_form', 'operation_form_id',
                    existing_type=mysql.INTEGER(display_width=11),
                    nullable=True)
    op.execute('SET foreign_key_checks = 1')
    # ### end Alembic commands ###
