"""plugin support

Revision ID: 95394e5f8107
Revises: aa8beb5ca6ac
Create Date: 2020-05-13 23:38:34.416638

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95394e5f8107'
down_revision = 'aa8beb5ca6ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_plugin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('version', sa.String(length=200), nullable=True),
    sa.Column('copyright', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('OUTDATED', 'DISABLED', 'ERROR', 'PENDING', 'INSTALLED', name='PluginStatusEnumType'), nullable=True),
    sa.Column('message', mysql.LONGTEXT(), nullable=True),
    sa.Column('manifest', mysql.LONGTEXT(), nullable=True),
    sa.Column('ids_offset', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('use_compiler', sa.Boolean(), nullable=False),
    sa.Column('use_executor', sa.Boolean(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platform.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('platform', sa.Column('plugin', sa.Boolean(), nullable=False))
    op.add_column('platform', sa.Column('version', sa.String(length=200), nullable=True))
    op.drop_column('workflow', 'publishing_enabled')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workflow', sa.Column('publishing_enabled', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
    op.drop_column('platform', 'version')
    op.drop_column('platform', 'plugin')
    op.drop_table('platform_plugin')
    # ### end Alembic commands ###
