""" New operation categories
"""
"""

Revision ID: 995d4fa1bfd0
Revises: b3c0fdaf659d
Create Date: 2017-05-22 10:59:42.902088

"""
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = '995d4fa1bfd0'
down_revision = 'b3c0fdaf659d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.execute(text('START TRANSACTION'))
        op.execute(text("UPDATE operation_category_translation "
                        "SET NAME = REPLACE(NAME, 'ML: ', '') "
                        "WHERE id BETWEEN 18 AND 26"))
        op.execute(text("UPDATE `operation_category` SET type = 'group' "
                        "WHERE type = 'parent' "))

        op.execute(text("UPDATE `operation_category` SET type = 'subgroup' "
                        "WHERE id BETWEEN 18 AND 26"))
        op.execute(text("""
            INSERT INTO
            operation_category_operation(operation_id, operation_category_id)
            SELECT operation_id, 8 FROM operation_category_operation
            WHERE operation_category_id BETWEEN 18 AND 26
        """))
        op.execute(text("""
            insert into operation_category_operation
            (operation_id, operation_category_id) values (39, 26)"""))
        op.execute(text("""update operation_category_operation
            set operation_category_id = 8 where operation_category_id = 1
                and operation_id = 39"""))
        op.execute(text("""update operation set enabled = 0 where id = 54;"""))
    except:
        op.execute(text('ROLLBACK'))
        raise

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.execute(text('START TRANSACTION'))
        op.execute(text("UPDATE operation_category_translation "
                        "SET NAME = CONCAT('ML: ', name) "
                        "WHERE id BETWEEN 18 AND 26 AND id <> 25"))
        op.execute(text("UPDATE `operation_category` SET type = 'parent' "
                        "WHERE type = 'group' OR type = 'subgroup' "))

        op.execute(text("""
            DELETE FROM operation_category_operation
            WHERE operation_category_id = 8
        """))
        op.execute(text("""DELETE FROM operation_category_operation
            WHERE operation_id = 39 AND operation_category_id = 26"""))
        op.execute(text("""update operation_category_operation
            set operation_category_id = 1 where operation_category_id = 1
                and operation_id = 39"""))
        op.execute(text("""update operation set enabled = 1 where id = 54;"""))
    except:
        op.execute(text('ROLLBACK'))
        raise
    # ### end Alembic commands ###
