"""add lemon main tables

Revision ID: cf0607926635
Revises: a237518ec5e1
Create Date: 2023-11-17 15:20:59.850985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf0607926635'
down_revision = 'a237518ec5e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Enum('ENABLED', 'DISABLED', name='AccessStatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('enabled', sa.Enum('ENABLED', 'DISABLED', name='AccessStatus'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_login', sa.String(length=50), nullable=False),
    sa.Column('user_name', sa.String(length=200), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('scheduling', sa.String(length=300), nullable=True),
    sa.Column('enabled', sa.Enum('ENABLED', 'DISABLED', name='AccessStatus'), nullable=False),
    sa.Column('status', sa.Enum('FAILURE', 'PARTIAL_SUCCESS', 'SUCCESS', 'CANCELLED', 'REJECTED', 'CREATED', name='ExecutionStatus'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipeline.id'], name='fk_pipeline_step_pipeline_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pipeline_step_pipeline_id'), 'pipeline_step', ['pipeline_id'], unique=False)
    op.create_table('template_pipeline_step',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('scheduling', sa.String(length=300), nullable=True),
    sa.Column('enabled', sa.Enum('ENABLED', 'DISABLED', name='AccessStatus'), nullable=False),
    sa.Column('status', sa.Enum('FAILURE', 'PARTIAL_SUCCESS', 'SUCCESS', 'CANCELLED', 'REJECTED', 'CREATED', name='ExecutionStatus'), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('templatepipeline_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['templatepipeline_id'], ['template_pipeline.id'], name='fk_template_pipeline_step_template_pipeline_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_template_pipeline_step_templatepipeline_id'), 'template_pipeline_step', ['templatepipeline_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_template_pipeline_step_templatepipeline_id'), table_name='template_pipeline_step')
    op.drop_table('template_pipeline_step')
    op.drop_index(op.f('ix_pipeline_step_pipeline_id'), table_name='pipeline_step')
    op.drop_table('pipeline_step')
    op.drop_table('template_pipeline')
    op.drop_table('pipeline')
    # ### end Alembic commands ###
