"""add identifier column to pipeline

Revision ID: ec6fa5b00b2d
Revises: 5dd9049584ac
Create Date: 2025-06-17 04:33:52.223316

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ec6fa5b00b2d'
down_revision = '5dd9049584ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pipeline', sa.Column('identifier', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pipeline', 'identifier')
    # ### end Alembic commands ###
