# -*- coding: utf-8 -*-}

"""operations

Revision ID: fcbcbd8ded43
Revises: 6821c3b11408
Create Date: 2017-05-02 18:02:00.673083

"""
from alembic import op
from sqlalchemy import String, Integer, Text
from sqlalchemy.sql import table, column, text
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'fcbcbd8ded43'
down_revision = '6821c3b11408'
branch_labels = None
depends_on = None


def upgrade():
    try:
        op.execute(text('START TRANSACTION'))
        insert_operation_form_field_translation()
        insert_operation_form_translation()
        insert_operation_operation_form()
        insert_platform()
        insert_operation_platform()
        insert_operation_translation()
        insert_platform_translation()
    except:
        op.execute(text('ROLLBACK'))
        raise


def insert_operation_form_field_translation():
    tb = table(
        'operation_form_field_translation',
        column('id', Integer),
        column('locale', String),
        column('label', String),
        column('help', String), )

    columns = ('id', 'locale', 'label', 'help')
    data = [
        (1, 'en', 'Data source', 'Data source to be used as input.'),
        (1, 'pt', 'Data source', 'Data source to be used as input.'),
        (6, 'en', 'Select attribute(s)',
         'Choose one or more attributes. These attributes will be selected to '
         'the output data set.'),
        (6, 'pt', 'Select attribute(s)',
         'Choose one or more attributes. These attributes will be selected to '
         'the output data set.'),
        (7, 'en', 'Max. execution memory (in MB)',
         'Max execution memory in megabytes. This is just a recommendation.'),
        (7, 'pt', 'Quantidade (em MB) máxima de memória reservada',
         'Quantidade (em MB) máxima de memória reservada'),
        (8, 'en', 'Max. execution time (seconds)',
         'Max execution time in seconds. This is just a recommendation.'),
        (8, 'pt', 'Tempo máximo de execução (em segundos) ',
         'Tempo máximo de execução (em segundos) '),
        (9, 'en', 'Max. number of CPUs',
         'Max number of CPUs. This is just a recommendation.'),
        (9, 'pt', 'Número máximo de CPUs', 'Número máximo de CPUs'),
        (10, 'en', 'Output data is sensitive',
         'Is the output data sensitive and should be protected?'),
        (10, 'pt', 'Dados de saída são sensíveis',
         'Dados de saída são sensíveis'),
        (11, 'en', 'Attribute(s) from first data source',
         'Select one or more attributes from the first data source'),
        (11, 'pt', 'Attribute(s) from first data source',
         'Select one or more attributes from the first data source'),
        (12, 'en', 'Attribute(s) from second data source',
         'Select one or more attributes from the second data source'),
        (12, 'pt', 'Attribute(s) from second data source',
         'Select one or more attributes from the second data source'),
        (13, 'en', 'Join type', 'Type of join to be performed.'),
        (13, 'pt', 'Join type', 'Type of join to be performed.'),
        (14, 'en', 'Keep keys from second data source',
         'Keys columns used in the join could be ignored because they are '
         'already present in the first data source.'),
        (14, 'pt', 'Keep keys from second data source',
         'Keys columns used in the join could be ignored because they are '
         'already present in the first data source.'),
        (15, 'en', 'Match case when comparing keys',
         'If checked, a case sensitive matching will be performed when '
         'comparing keys.'),
        (15, 'pt', 'Match case when comparing keys',
         'If checked, a case sensitive matching will be performed when '
         'comparing keys.'),
        (16, 'en', 'Weights', 'Weights used to split the data source'),
        (16, 'pt', 'Weights', 'Weights used to split the data source'),
        (17, 'en', 'Seed',
         'Seed used to initialize the random number generator.'),
        (17, 'pt', 'Seed',
         'Seed used to initialize the random number generator.'),
        (18, 'en', 'Attribute(s)',
         'Select one or more attributes to be cleaned'),
        (18, 'pt', 'Attribute(s)',
         'Select one or more attributes to be cleaned'),
        (19, 'en', 'Cleaning mode', 'Type of cleaning to be performed.'),
        (19, 'pt', 'Cleaning mode', 'Type of cleaning to be performed.'),
        (20, 'en', 'Value', 'Value used to replace missing values.'),
        (20, 'pt', 'Value', 'Value used to replace missing values.'),
        (21, 'en', 'Comment', 'Just a comment to be shown in the diagram'),
        (21, 'pt', 'Comentário', 'Comentário'),
        (22, 'en', 'Comment', 'Comment'),
        (22, 'pt', 'Comment', 'Comment'),
        (23, 'en', 'Attribute(s)',
         'Select one or more attributes to be used as sort criteria. '
         'Order matters.'),
        (23, 'pt', 'Attribute(s)',
         'Select one or more attributes to be used as sort criteria. '
         'Order matters.'),
        (25, 'en', 'Color', 'Background color'),
        (25, 'pt', 'Cor', 'Cor de fundo'),
        (26, 'en', 'Attribute(s)', 'Select one or more attributes.'),
        (26, 'pt', 'Atributo(s)', 'Selecione um ou mais atributos.'),
        (61, 'en', 'New name',
         'New name. If used with multiple attributes, a numerical '
         'suffix will be used to distinguish them. For example, name1, name2'
         ', ...\r\nYou can use the variable ${attribute_name} to rename '
         'attributes by adding a prefix or a suffix to the original name.'),
        (61, 'pt', 'Novo nome',
         'Novo nome. Se usado com vários atributos, o nome será o sufixo.'),
        (62, 'en', 'New data type',
         'New data type. A conversion is not performed and if you incorrectly '
         'change this information, the workflow may not work.'),
        (62, 'pt', 'Novo tipo de dados',
         'Novo tipo dos dados. Nenhuma conversão é realizada.'),
        (63, 'en', 'Mark as Noneable', 'Is attribute Noneable?'),
        (63, 'pt', 'Marcar como podendo ser nulo', 'Atributo pode ser nulo'),
        (64, 'en', 'Mark as feature', 'Attributes are feature'),
        (64, 'pt', 'Marcar como feature',
         'Atributos são features (características)'),
        (65, 'en', 'Mark as label', 'Attributes are label'),
        (65, 'pt', 'Marcar como rótulo', 'Atributos são rótulos (labels)'),
        (67, 'en', 'Log level', 'Log level'),
        (67, 'pt', 'Nível de registro', 'Nível de registro'),
        (68, 'en', 'Available applications', 'Application to be executed'),
        (68, 'pt', 'Aplicações disponíveis', 'Aplicação a ser executada'),
        (69, 'en', 'Parameters', 'Application parameters'),
        (69, 'pt', 'Parâmertos', 'Parâmetros da aplicação'),
        (70, 'en', 'Select attribute(s) for aggregation',
         'Choose one or more attributes to aggregate data with'),
        (70, 'pt', 'Selecione o(s) atributos para agregação',
         'Escola um ou mais atributos para a agregação.'),
        (71, 'en', 'Aggregation function',
         'Function applied to aggregated data'),
        (71, 'pt', 'Função de agregação',
         'Função a ser aplicada aos dados agregados'),
        (72, 'en', 'Key fields',
         'Choose zero or more fields to be used as key. If no field is choosen,'
         ' all fields are used'),
        (72, 'pt', 'Campos-chave',
         'Escolha zero ou mais campos para serem usados como chave durante a '
         'operação. Se nenhum campo for informado, todos os campos serão '
         'considerados como parte da chave'),
        (73, 'en', 'Seed',
         'Seed used to initialize the random number generator.'),
        (73, 'pt', 'Semente para num. aleatório',
         'Semente para a geração do número aleatório'),
        (74, 'en', 'percentage', 'Percentage of data to be sampled'),
        (74, 'pt', 'percentual', 'Percentual dos dados a ser amostrado'),
        (75, 'en', 'Use first line as header',
         'Does file first line contain header information about attributes?'),
        (75, 'pt', 'Use first line as header',
         'Does file first line contain header information about attributes?'),
        (76, 'en', 'Attribute separator',
         'Character used as attribute separator'),
        (76, 'pt', 'Attribute separator',
         'Character used as attribute separator'),
        (77, 'en', 'Infer data source schema',
         'Infer data source schema from attribute\'s values.'),
        (77, 'pt', 'Infer data source schema',
         'Infer data source schema from attribute\'s values.'),
        (78, 'en', 'Select 2 attribute',
         'Choose exactly 2 attributes. These attributes will be used in '
         'correlation.'),
        (78, 'pt', 'Selecione 2 atributos',
         'Selecione exatamente 2 atributos. Estes atributos serão usados na '
         'correlação.'),
        (79, 'en', 'Minimum missing value ratio',
         'Minimum number of missing values required for the operation to be'
         ' performed'),
        (79, 'pt', 'Razão mínima de valores ausentes',
         'Razão mínima entre o total de valores ausentes e o total de registros'
         ' a ser considerada para que a operação seja executada'),
        (80, 'en', 'Maximum missing value ratio',
         'Maximum number of missing values that can be present for the '
         'operation to be performed'),
        (80, 'pt', 'Razão máxima de valores ausentes',
         'Razão máxima entre o total de valores ausentes e o total de registros'
         ' a ser considerada para que a operação seja executada'),
        (81, 'en', 'Data source name', 'Data source name'),
        (81, 'pt', 'Data source name', 'Data source name'),
        (82, 'en', 'Data source path (relative to storage)',
         'Path for data source'),
        (82, 'pt', 'Data source path (relative to storage)',
         'Path for data source'),
        (83, 'en', 'Output format', 'Output format used to write data'),
        (83, 'pt', 'Output format', 'Output format used to write data'),
        (84, 'en', 'Tags', 'Tags	'),
        (84, 'pt', 'Tags', 'Tags	'),
        (85, 'en', 'Overwrite mode',
         'Action in case of trying to write over an existing file'),
        (85, 'pt', 'Overwrite mode',
         'Action in case of trying to write over an existing file'),
        (86, 'en', 'Save header', 'Save header information if format is CSV'),
        (86, 'pt', 'Save header', 'Save header information if format is CSV'),
        (87, 'en', 'Storage', 'Storage where data is saved'),
        (87, 'pt', 'Storage', 'Storage where data is saved'),
        (88, 'en', 'Expression',
         'Expression to apply to an attribute in order to generate another '
         'attribute. See help for supported functions and syntax.'),
        (88, 'pt', 'Expression',
         'Expression to apply to an attribute in order to generate another '
         'attribute. See help for supported functions and syntax.'),
        (89, 'en', 'Name for transformed attribute',
         'Name for the transformed attribute.'),
        (89, 'pt', 'Name for transformed attribute',
         'Name for the transformed attribute.'),
        (90, 'en', 'Filter', 'Filter'),
        (90, 'pt', 'Filtro', 'Filtro'),
        (91, 'en', 'Treat these values as None (comma-separated)',
         'These values will be considered as None when parsing the file. '
         'Separe items by comma (,).'),
        (91, 'pt', 'Tratar esses valores como nulos (separe por vírgula)',
         'Esses valores serão considerados como nulos quando o arquivo '
         'estiver sendo lido. Separe os valores por vírgula (,).'),
        (93, 'en', 'Attributes', 'Attributes (features) to be indexed'),
        (93, 'pt', 'Atributos', 'Atributos (features) a ser indexados'),
        (94, 'en', 'Indexer type', 'Indexer type'),
        (94, 'pt', 'Tipo de indexador', 'Tipo de indexador'),
        (95, 'en', 'Name for new indexed attribute(s)',
         'Name for new indexed attribute(s)'),
        (95, 'pt', 'Nome para novo(s) atributo(s) indexado(s)',
         'Nome para novo(s) atributo(s) indexado(s)'),
        (96, 'en', 'Max. categories (vector only)',
         'Max. categories (vector only)'),
        (96, 'pt', 'Máx. categorias (vetor apenas)',
         'Máx. categorias (vetor apenas)'),
        (97, 'en', 'Attributes to be assembled', 'Attributes to be assembled'),
        (98, 'en', 'New attribute name', 'New attribute name'),
        (99, 'en', 'Prediction attribute', 'Prediction attribute'),
        (100, 'en', 'Label attribute', 'Label attribute'),
        (101, 'en', 'Metric to evaluation', 'Metric to evaluation'),
        (102, 'en', 'Type of sampling or partition',
         'Type of sampling or partition'),
        (103, 'en', 'Folds',
         'How many folds will be generated. Data will be distributed as '
         'equaly as possible among folds.'),
        (104, 'en', 'Fold size',
         'How many records will be distributed among folds. The number of '
         'folds will depend on the number of records.'),
        (105, 'en', 'Total of records', 'Total of records to be retrieved'),
        (106, 'en', 'Estimator', 'Estimator'),
        (107, 'en', 'Evaluator', 'Evaluator'),
        (108, 'en', 'Folds', 'Folds'),
        (109, 'en', 'Seed', 'Seed used to generate folds'),
        (110, 'en', 'Optimizer', 'Optimizer'),
        (111, 'en', 'Type', 'Type of tokenizer'),
        (112, 'en', 'Expression (only if type regex)',
         'Expression (only if type regex) for regular expression '
         '(Java syntax)'),
        (113, 'en', 'Minimum size of tokens',
         'Any token smaller than this value will be discarded'),
        (114, 'en', 'Attributes',
         'List of attributes to be used as input to remove stop words'),
        (115, 'en', 'Alias for new attributes', 'Alias for new attributes'),
        (116, 'en', 'Stop word list', 'Stop word list, separated by commas'),
        (117, 'en', 'Attribute from 2nd input with stop words',
         'Attribute from 2nd input with stop words'),
        (118, 'en', 'Case sensitive', 'Case sensitive'),
        (118, 'pt', 'Diferenciar maiúsculas/minúsculas',
         'Diferenciar maiúsculas/minúsculas'),
        (119, 'en', 'Attributes', 'Attributes'),
        (120, 'en', 'Alias', 'ALias'),
        (121, 'en', 'Attributes', 'Attributes'),
        (122, 'en', 'Alias', 'Alias'),
        (123, 'en', 'Type', 'Type'),
        (123, 'pt', 'Tipo', 'Tipo'),
        (124, 'en', 'Vocabulary size', 'Vocabulary size'),
        (124, 'pt', 'Tamanho do vocabulário', 'Tamanho do vocabulário'),
        (125, 'en', 'Minimum frequency in docs (DF)',
         'Minimum frequency in docs (DF)'),
        (125, 'pt', 'Frequência mínima de documentos (DF)', None),
        (126, 'en', 'Number of topics (K)',
         'Number of topics (K) to be generated'),
        (127, 'en', 'Max. iterations', 'Max. iterations'),
        (127, 'pt', 'Número máx. de iterações', 'Número máx. de iterações'),
        (128, 'en', 'Minimum term frequency (TF)',
         'Minimum term frequency (TF)'),
        (128, 'pt', 'Frequência mínima do termo (TF)',
         'Frequência mínima do termo (TF)'),
        (130, 'en', 'Features attribute', 'Features attribute'),
        (131, 'en', 'Label attribute', 'Label attribute'),
        (132, 'en', 'Features attribute', 'Features attribute'),
        (133, 'en', 'Shapefile', 'Shapefile'),
        (134, 'en', 'Features', 'Features'),
        (135, 'en', 'Label', 'Label'),
        (135, 'pt', 'Rótulo', None),
        (136, 'en', 'Smoothing', 'Smoothing'),
        (136, 'pt', 'Suavização', None),
        (137, 'en', 'Features', 'Label'),
        (137, 'pt', 'Features', None),
        (138, 'en', 'Label', 'Label'),
        (138, 'pt', 'Rótulo', None),
        (140, 'en', 'Features', 'Label'),
        (140, 'pt', 'Features', None),
        (141, 'en', 'Label', 'Label'),
        (141, 'pt', 'Rótulo', None),
        (143, 'en', 'Features', 'Label'),
        (143, 'pt', 'Features', None),
        (144, 'en', 'Label', None),
        (144, 'pt', 'Rótulo', None),
        (146, 'en', 'Features', 'Features'),
        (146, 'pt', 'Features', 'Features'),
        (147, 'en', 'Label', 'Label'),
        (147, 'pt', 'Rótulo', 'Rótulo'),
        (149, 'en', 'Impurity',
         'Impurity is the measure based on which the (locally) optimal '
         'condition is chosen.'),
        (149, 'pt', 'Impureza',
         'Impureza é a medida na qual o algoritmo se base para escolher '
         'a condição ótima local'),
        (150, 'en', 'Report name', 'Report name'),
        (150, 'pt', 'Nome do relatório', 'Nome do relatório'),
        (152, 'en', 'Terms per topic (max)', 'Terms per topic (max)'),
        (153, 'en', 'Terms per topic (max)', 'Terms per topic (max)'),
        (153, 'pt', 'Termos por tópico (máx)', 'Termos por tópico (máx)'),
        (154, 'en', 'Latitude', 'Latitude'),
        (154, 'pt', 'Latitude', 'Latitude'),
        (155, 'en', 'Polygon attribute in geo data',
         'Polygon attribute in geo data'),
        (155, 'pt', 'Atributo com o polígono nos dados geo',
         'Atributo com o polígono nos dados geo'),
        (156, 'en', 'Number of clusters (K)', 'Number of clusters (K)'),
        (156, 'pt', 'Quantidade de agrupamentos (K)',
         'Quantidade de agrupamentos (K)'),
        (157, 'en', 'Type', 'Type'),
        (157, 'pt', 'Tipo', 'Tipo'),
        (158, 'en', 'Init mode', 'How to generate initial centroids'),
        (158, 'pt', 'Geração dos centroids iniciais',
         'Geração dos centroids iniciais'),
        (159, 'en', 'Max iterations', 'Max iterations'),
        (159, 'pt', 'Número máx. de iterações', 'Número máx. de iterações'),
        (160, 'en', 'Tolerance',
         'Convergency tolerance for the within-cluster sums of point-to-'
         'centroid distances.'),
        (160, 'pt', 'Tolerância',
         'Tolerância de convergência para as somas das distâncias intra-'
         'cluster do ponto ao centroide.'),
        (161, '', None, None),
        (161, 'en', 'Number of clusters (K)', 'Number of clusters (K)'),
        (162, 'en', 'Max iterations', 'Max iterations'),
        (162, 'pt', 'Número máx. de iterações', 'Número máx. de iterações'),
        (163, 'en', 'Tolerance',
         'Convergency tolerance for the within-cluster sums of point-to-'
         'centroid distances.'),
        (163, 'pt', 'Tolerância',
         ' Tolerância de convergência para as somas das distâncias intra-'
         'cluster do ponto ao centroide.'),
        (164, 'en', 'Number of elements per n-gram',
         'Number of elements per n-gram (>=2)'),
        (164, 'pt', 'Número de elementos por n-grama',
         'Número de elementos por n-grama (>=2)'),
        (165, 'en', 'Attributes', 'Attributes'),
        (165, 'pt', 'Atributos', 'Attributos'),
        (166, 'en', 'Name(s) of new attribute(s)',
         'Name(s) of new attribute(s)'),
        (166, 'pt', 'Nome(s) do(s) novo(s) attributo(s)',
         'Nome(s) do(s) novo(s) attributo(s)'),
        (167, 'en', 'Longitude', 'Longitude'),
        (167, 'pt', 'Longitude', 'Longitude'),
        (168, 'en', 'Attributes to retrieve from shapefile',
         'Attributes to retrieve from shapefile'),
        (168, 'pt', 'Atributos a recuperar do shapefile',
         'Atributos a recuperar do shapefile'),
        (169, 'en', 'Alias for shapefile attributes',
         'Alias for shapefile attributes'),
        (169, 'pt', 'Nomes para atributos do shapefile',
         'Nomes para atributos do shapefile'),
        (170, 'en', 'Document concentration (alpha)',
         'Document concentration (alpha)'),
        (170, 'pt', 'Concentração de documentos (alfa)',
         'Concentração de documentos (alfa)'),
        (171, 'en', 'Topic concentration (beta)', 'Topic concentration (beta)'),
        (171, 'pt', 'Concentração de tópicos (beta)',
         'Concentração de tópicos (beta)'),
        (172, 'en', 'Attributes', 'Attributes'),
        (172, 'pt', 'Atributos', 'Atributos'),
        (173, 'en', 'Type', 'Type of external input'),
        (173, 'pt', 'Tipo', 'Tipo de entrada externa'),
        (174, 'en', 'Choose input 2 if condition true',
         'Choose input 2 if condition true'),
        (174, 'pt', 'Escolha entrada 2 se condição verdadeira',
         'Escolha entrada 2 se condição verdadeira'),
        (175, 'en', 'Data source', 'Data source to be used as input.'),
        (175, 'pt', 'Fonte de dados',
         'Fonte de dados a ser usada como entrada'),
        (176, 'en', 'Filter', 'Filter'),
        (176, 'pt', 'Filtro', 'Filtro'),
        (177, 'en', 'Factorization number (rank)',
         'Factorization number (rank)'),
        (177, 'pt', 'Número de fatorização (rank)',
         'Número de fatorização (rank)'),
        (178, 'en', 'Max iterations', 'Max iterations'),
        (178, 'pt', 'Iterações', 'Iterações'),
        (179, 'en', 'User id attribute', 'User id attribute'),
        (179, 'pt', 'Atributo com id do usuário', 'Atributo com id do usuário'),
        (180, 'en', 'Evaluated item id attrbiute',
         'Evaluated item id attribute'),
        (180, 'pt', 'Atributo com id do item avaliado',
         'Atributo com id do item avaliado'),
        (181, 'en', 'Attribute with evaluation', 'Attribute with evaluation'),
        (181, 'pt', 'Atributo com a avaliação', 'Atributo com a avaliação'),
        (182, 'en', 'Experiment regularization', 'Experiment regularization'),
        (182, 'pt', 'Regularização do experimento',
         'Regularização do experimento'),
        (183, 'en', 'Features', 'Features'),
        (183, 'pt', 'Features', 'Features'),
        (184, 'en', 'Label', 'Label'),
        (184, 'pt', 'Rótulo', 'Rótulo'),
        (185, 'en', 'Prediction attribute', 'Prediction attribute'),
        (185, 'pt', 'Predição (novo atributo)', 'Predição (novo atributo)'),
        (186, 'en', 'Weight attribute', 'Weight attribute'),
        (186, 'pt', 'Atributo com os pesos', 'Atributo com os pesos'),
        (187, 'en', 'Family', 'Family'),
        (187, 'pt', 'Família', 'Família'),
        (188, 'en', 'Title', 'Title'),
        (188, 'pt', 'Título', 'Título'),
        (189, 'en', 'Labels',
         'Labels. If omitted, id attribute values will be used.'),
        (189, 'pt', 'Rótulos',
         'Rótulos. Se omitido, os valores do atributo id serão usados.'),
        (190, 'en', 'Id attribute (x-axis)', 'Id attribute (x-axis)'),
        (190, 'pt', 'Atributo (x-axis)', 'Atributo (x-axis)'),
        (191, 'en', 'Value atribute', 'Value atribute'),
        (191, 'pt', 'Atributo com o valor', 'Atributo com o valor'),
        (192, 'en', 'Orientation', 'Orientation'),
        (192, 'pt', 'Orientação', 'Orientação')
    ]
    rows = [dict(list(zip(columns, row))) for row in data]

    op.bulk_insert(tb, rows)


def insert_operation_form_translation():
    tb = table(
        'operation_form_translation',
        column('id', Integer),
        column('locale', String),
        column('name', String))

    columns = ('id', 'locale', 'name')
    data = [
        (1, 'en', 'Execution'),
        (1, 'pt', 'Execução'),
        (2, 'en', 'Execution'),
        (2, 'pt', 'Execução'),
        (3, 'en', 'Execution'),
        (3, 'pt', 'Execução'),
        (4, 'en', 'Execution'),
        (4, 'pt', 'Execução'),
        (5, 'en', 'Execution'),
        (5, 'pt', 'Execução'),
        (6, 'en', 'Execution'),
        (6, 'pt', 'Execução'),
        (7, 'en', 'Execution'),
        (7, 'pt', 'Execução'),
        (8, 'en', 'Execution'),
        (8, 'pt', 'Execução'),
        (9, 'en', 'Execution'),
        (9, 'pt', 'Execução'),
        (10, 'en', 'Execution'),
        (10, 'pt', 'Execução'),
        (11, 'en', 'Execution'),
        (11, 'pt', 'Execução'),
        (12, 'en', 'Execution'),
        (12, 'pt', 'Execução'),
        (13, 'en', 'Execution'),
        (13, 'pt', 'Execução'),
        (14, 'en', 'Execution'),
        (14, 'pt', 'Execução'),
        (15, 'en', 'Execution'),
        (15, 'pt', 'Execução'),
        (16, 'en', 'Execution'),
        (16, 'pt', 'Execução'),
        (17, 'en', 'Execution'),
        (17, 'pt', 'Execução'),
        (18, 'en', 'Execution'),
        (18, 'pt', 'Execução'),
        (19, 'en', 'Execution'),
        (19, 'pt', 'Execução'),
        (20, 'en', 'Execution'),
        (20, 'pt', 'Execução'),
        (21, 'en', 'Execution'),
        (21, 'pt', 'Execução'),
        (22, 'en', 'Execution'),
        (22, 'pt', 'Execução'),
        (23, 'en', 'Execution'),
        (23, 'pt', 'Execução'),
        (24, 'en', 'Execution'),
        (24, 'pt', 'Execução'),
        (25, 'en', 'Execution'),
        (25, 'pt', 'Execução'),
        (26, 'en', 'Execution'),
        (26, 'pt', 'Execução'),
        (27, 'en', 'Execution'),
        (27, 'pt', 'Execução'),
        (28, 'en', 'Execution'),
        (28, 'pt', 'Execução'),
        (32, 'en', 'Execution'),
        (32, 'pt', 'Execução'),
        (33, 'en', 'Execution'),
        (33, 'pt', 'Execução'),
        (34, 'en', 'Execution'),
        (34, 'pt', 'Execução'),
        (35, 'en', 'Execution'),
        (35, 'pt', 'Execução'),
        (39, 'en', 'Infrastructure/QoS'),
        (39, 'pt', 'Infraestrutura/QoS'),
        (40, 'en', 'Security and Privacy'),
        (40, 'pt', 'Segurança e privacidade'),
        (41, 'en', 'Appearance'),
        (41, 'pt', 'Aparência'),
        (42, 'en', 'Execution'),
        (42, 'pt', 'Execução'),
        (43, 'en', 'Logging'),
        (43, 'pt', 'Registro de execução'),
        (44, 'en', 'Execution'),
        (44, 'pt', 'Execução'),
        (45, 'en', 'Execution'),
        (45, 'pt', 'Execução'),
        (46, 'en', 'Execution'),
        (46, 'pt', 'Execução'),
        (48, 'en', 'Execution'),
        (48, 'pt', 'Execução'),
        (49, 'en', 'Execution'),
        (49, 'pt', 'Execução'),
        (50, 'en', 'Execution'),
        (50, 'pt', 'Execution'),
        (51, 'en', 'Execution'),
        (51, 'pt', 'Execução'),
        (52, 'en', 'Execution'),
        (52, 'pt', 'Execução'),
        (53, 'en', 'Execution'),
        (53, 'pt', 'Execução'),
        (54, 'en', 'Execution'),
        (54, 'pt', 'Execução'),
        (55, 'en', 'Execution'),
        (55, 'pt', 'Execução'),
        (56, 'en', 'Execution'),
        (56, 'pt', 'Execução'),
        (57, 'en', 'Execution'),
        (57, 'pt', 'Execução'),
        (58, 'en', 'Execution'),
        (58, 'pt', 'Execução'),
        (59, 'en', 'Execution'),
        (59, 'pt', 'Execução'),
        (60, 'en', 'Execution'),
        (60, 'pt', 'Execução'),
        (61, 'en', 'Execution'),
        (61, 'pt', 'Execução'),
        (62, 'en', 'Execution'),
        (62, 'pt', 'Execução'),
        (63, 'en', 'Execution'),
        (63, 'pt', 'Execução'),
        (64, 'en', 'Param grid'),
        (64, 'pt', 'Grade de parâmetros'),
        (65, 'en', 'Param grid'),
        (65, 'pt', 'Grade de parâmetros'),
        (66, 'en', 'Param grid'),
        (66, 'pt', 'Grade de parâmetros'),
        (67, 'en', 'Param grid'),
        (67, 'pt', 'Grade de parâmetros'),
        (68, 'en', 'Param grid'),
        (68, 'pt', 'Grade de parâmetros'),
        (69, 'en', 'Execution'),
        (69, 'pt', 'Execução'),
        (70, 'en', 'Execution'),
        (70, 'pt', 'Execução'),
        (71, 'en', 'Execution'),
        (71, 'pt', 'Execução'),
        (72, 'en', 'Execution'),
        (72, 'pt', 'Execução'),
        (73, 'en', 'Execution'),
        (73, 'pt', 'Execução'),
        (74, 'en', 'Execution'),
        (74, 'pt', 'Execução'),
        (75, 'en', 'Execution'),
        (75, 'pt', 'Execução'),
        (76, 'en', 'Execution'),
        (76, 'pt', 'Execução'),
        (77, 'en', 'Execution'),
        (77, 'pt', 'Execução'),
        (78, 'en', 'Execution'),
        (78, 'pt', 'Execução'),
        (79, 'en', 'Execution'),
        (79, 'pt', 'Execução'),
        (80, 'en', 'Execution'),
        (80, 'pt', 'Execução'),
        (81, 'en', 'Execution'),
        (81, 'pt', 'Execução'),
        (82, 'en', 'Execution'),
        (82, 'pt', 'Execução'),
        (83, 'en', 'Execution'),
        (83, 'pt', 'Execução'),
        (84, 'en', 'Execution'),
        (84, 'pt', 'Execução'),
        (85, 'en', 'Execution'),
        (85, 'pt', 'Execução'),
        (86, 'en', 'Execution'),
        (86, 'pt', 'Execução')
    ]
    rows = [dict(list(zip(columns, row))) for row in data]

    op.bulk_insert(tb, rows)


def insert_operation_operation_form():
    tb = table(
        'operation_operation_form',
        column('operation_id', Integer),
        column('operation_form_id', Integer))

    columns = ('operation_id', 'operation_form_id')
    data = [
        (1, 1),
        (2, 2),
        (3, 3),
        (5, 5),
        (6, 6),
        (6, 39),
        (6, 40),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10),
        (11, 11),
        (13, 13),
        (14, 14),
        (15, 15),
        (16, 16),
        (17, 17),
        (17, 41),
        (18, 18),
        (19, 32),
        (20, 19),
        (21, 20),
        (22, 21),
        (23, 22),
        (26, 25),
        (27, 33),
        (28, 26),
        (29, 27),
        (30, 28),
        (31, 34),
        (32, 35),
        (1, 39),
        (2, 39),
        (3, 39),
        (4, 39),
        (5, 39),
        (7, 39),
        (8, 39),
        (9, 39),
        (10, 39),
        (11, 39),
        (12, 39),
        (13, 39),
        (14, 39),
        (15, 39),
        (16, 39),
        (17, 39),
        (18, 39),
        (19, 39),
        (20, 39),
        (21, 39),
        (22, 39),
        (23, 39),
        (24, 39),
        (26, 39),
        (27, 39),
        (28, 39),
        (29, 39),
        (30, 39),
        (31, 39),
        (32, 39),
        (1, 40),
        (2, 40),
        (3, 40),
        (4, 40),
        (5, 40),
        (7, 40),
        (8, 40),
        (9, 40),
        (10, 40),
        (11, 40),
        (12, 40),
        (13, 40),
        (14, 40),
        (15, 40),
        (16, 40),
        (17, 40),
        (18, 40),
        (19, 40),
        (20, 40),
        (21, 40),
        (22, 40),
        (23, 40),
        (24, 40),
        (26, 40),
        (27, 40),
        (28, 40),
        (29, 40),
        (30, 40),
        (31, 40),
        (32, 40),
        (1, 41),
        (2, 41),
        (3, 41),
        (4, 41),
        (5, 41),
        (6, 41),
        (7, 41),
        (8, 41),
        (9, 41),
        (10, 41),
        (11, 41),
        (12, 41),
        (13, 41),
        (14, 41),
        (15, 41),
        (16, 41),
        (18, 41),
        (19, 41),
        (20, 41),
        (21, 41),
        (22, 41),
        (23, 41),
        (24, 41),
        (25, 41),
        (26, 41),
        (27, 41),
        (28, 41),
        (29, 41),
        (30, 41),
        (31, 41),
        (32, 41),
        (33, 42),
        (33, 41),
        (1, 43),
        (2, 43),
        (3, 43),
        (4, 43),
        (5, 43),
        (6, 43),
        (7, 43),
        (8, 43),
        (9, 43),
        (10, 43),
        (11, 43),
        (12, 43),
        (13, 43),
        (14, 43),
        (15, 43),
        (16, 43),
        (17, 43),
        (18, 43),
        (19, 43),
        (20, 43),
        (21, 43),
        (22, 43),
        (23, 43),
        (24, 43),
        (25, 43),
        (26, 43),
        (27, 43),
        (28, 43),
        (29, 43),
        (30, 43),
        (31, 43),
        (32, 43),
        (33, 43),
        (34, 41),
        (34, 43),
        (35, 45),
        (35, 41),
        (35, 43),
        (36, 46),
        (36, 41),
        (36, 43),
        (37, 41),
        (37, 43),
        (38, 48),
        (38, 41),
        (38, 43),
        (39, 49),
        (39, 41),
        (39, 43),
        (40, 41),
        (40, 39),
        (40, 43),
        (40, 40),
        (40, 50),
        (41, 41),
        (41, 39),
        (41, 43),
        (41, 40),
        (41, 51),
        (42, 41),
        (42, 39),
        (42, 43),
        (42, 40),
        (42, 52),
        (43, 41),
        (43, 39),
        (43, 43),
        (43, 40),
        (43, 53),
        (44, 41),
        (44, 39),
        (44, 43),
        (44, 40),
        (45, 41),
        (45, 39),
        (45, 43),
        (45, 40),
        (46, 41),
        (46, 39),
        (46, 43),
        (46, 40),
        (47, 41),
        (47, 39),
        (47, 43),
        (47, 40),
        (48, 41),
        (48, 39),
        (48, 43),
        (48, 40),
        (48, 58),
        (49, 41),
        (49, 39),
        (49, 43),
        (49, 40),
        (49, 59),
        (50, 41),
        (50, 39),
        (50, 43),
        (50, 40),
        (50, 60),
        (51, 41),
        (51, 39),
        (51, 43),
        (51, 40),
        (51, 61),
        (52, 41),
        (52, 39),
        (52, 43),
        (52, 40),
        (52, 62),
        (53, 41),
        (53, 39),
        (53, 43),
        (53, 40),
        (53, 63),
        (4, 64),
        (44, 65),
        (46, 66),
        (45, 67),
        (47, 68),
        (54, 41),
        (54, 39),
        (54, 43),
        (54, 40),
        (54, 69),
        (55, 41),
        (55, 39),
        (55, 43),
        (55, 40),
        (55, 70),
        (56, 41),
        (56, 39),
        (56, 43),
        (56, 40),
        (56, 71),
        (57, 41),
        (57, 39),
        (57, 43),
        (57, 40),
        (57, 72),
        (58, 41),
        (58, 39),
        (58, 43),
        (58, 40),
        (58, 73),
        (59, 41),
        (59, 39),
        (59, 43),
        (59, 40),
        (59, 74),
        (60, 41),
        (60, 39),
        (60, 43),
        (60, 40),
        (60, 75),
        (61, 76),
        (62, 77),
        (63, 78),
        (64, 79),
        (65, 80),
        (66, 81),
        (67, 82),
        (61, 41),
        (62, 41),
        (63, 41),
        (64, 41),
        (65, 41),
        (66, 41),
        (67, 41),
        (68, 41),
        (68, 39),
        (68, 43),
        (68, 40),
        (68, 83),
        (69, 41),
        (69, 39),
        (69, 43),
        (69, 40),
        (69, 84),
        (70, 41),
        (70, 39),
        (70, 43),
        (70, 40),
        (70, 85),
        (71, 41),
        (71, 39),
        (71, 43),
        (71, 40),
        (71, 86)
    ]
    rows = [dict(list(zip(columns, row))) for row in data]

    op.bulk_insert(tb, rows)


def insert_operation_platform():
    tb = table(
        'operation_platform',
        column('operation_id', Integer),
        column('platform_id', Integer))

    columns = ('operation_id', 'platform_id')
    data = [
        (1, 1),
        (2, 1),
        (3, 1),
        (4, 1),
        (5, 1),
        (6, 1),
        (7, 1),
        (8, 1),
        (9, 1),
        (10, 1),
        (11, 1),
        (12, 1),
        (13, 1),
        (14, 1),
        (15, 1),
        (16, 1),
        (17, 1),
        (18, 1),
        (19, 1),
        (20, 1),
        (21, 1),
        (22, 1),
        (23, 1),
        (24, 1),
        (25, 1),
        (26, 1),
        (27, 1),
        (28, 1),
        (29, 1),
        (30, 1),
        (31, 1),
        (32, 1),
        (33, 1),
        (34, 1),
        (35, 1),
        (36, 1),
        (37, 1),
        (38, 1),
        (39, 1),
        (40, 1),
        (41, 1),
        (42, 1),
        (43, 1),
        (44, 1),
        (45, 1),
        (46, 1),
        (47, 1),
        (48, 1),
        (49, 1),
        (50, 1),
        (51, 1),
        (52, 1),
        (53, 1),
        (54, 1),
        (55, 1),
        (56, 1),
        (57, 1),
        (58, 1),
        (59, 1),
        (60, 1),
        (68, 1),
        (69, 1),
        (70, 1),
        (71, 1)
    ]
    rows = [dict(list(zip(columns, row))) for row in data]

    op.bulk_insert(tb, rows)


def insert_platform():
    tb = table(
        'platform',
        column('id', Integer),
        column('slug', String),
        column('enabled', Integer),
        column('icon', String), )

    columns = ('id', 'slug', 'enabled', 'icon')
    data = [
        (1, 'spark', 1, '/static/spark.png'),
        (2, 'ophidia', 0, ''),
        (3, 'compss', 0, '')
    ]
    rows = [dict(list(zip(columns, row))) for row in data]

    op.bulk_insert(tb, rows)


def insert_operation_translation():
    tb = table(
        'operation_translation',
        column('id', Integer),
        column('locale', String),
        column('name', String),
        column('description', String), )

    columns = ('id', 'locale', 'name', 'description')
    data = [
        (1, 'en', 'Classification model',
         'Trains and applies a classification model'),
        (1, 'pt', 'Modelo de classificação',
         'Treina e aplica um modelo de classificação'),
        (2, 'en', 'Topic report', 'Topic report'),
        (2, 'pt', 'Relatório de tópicos', 'Relatório de tópicos'),
        (3, 'en', 'Frequent itemsets mining',
         'Identifies frequent itemsets in transactions'),
        (3, 'pt', 'Mineiração de itemsets freq.',
         'Identifica conjuntos de itens frequentes em transações'),
        (4, 'en', 'Naive Bayes classifier',
         'Naive Bayes Classifiers. It supports both Multinomial and Bernoulli '
         'NB. Multinomial NB can handle finitely supported discrete data. '
         'For example, by converting documents into TF-IDF vectors, '
         'it can be '),
        (4, 'pt', 'Classificador Naive Bayes', 'Usa um classificador'),
        (5, 'en', 'Filter (selection)',
         'Filters data according to some criteria'),
        (5, 'pt', 'Filtrar (seleção)',
         'Filtra linhas da fonte de dados de acordo com algum critério'),
        (6, 'en', 'Projection/Select columns',
         'Selects a subset of the fields from data set'),
        (6, 'pt', 'Projeção/Selecionar atributos',
         'Seleciona um subconjunto de attributos da fonte de dados'),
        (7, 'en', 'Transformation', 'Performs a data transformation'),
        (7, 'pt', 'Transformar', 'Realiza uma transformação nos dados'),
        (8, 'en', 'Linear regression', 'Applies a linear regression algorithm'),
        (8, 'pt', 'Regressão linear', 'Aplica a regressão linear'),
        (9, 'en', 'SVM Classification', 'Uses a SVM Classifier'),
        (9, 'pt', 'Classificador SVM', 'Usa um classificador SVM'),
        (10, 'en', 'Clustering model', 'Trains and applies a clustering model'),
        (10, 'pt', 'Modelo de agrupamento',
         'Treina e aplica um modelo de agrupamento'),
        (11, 'en', 'Outlier detection', 'Performs outlier detection'),
        (11, 'pt', 'Detectar outliers', 'Realiza a detecção de outliers'),
        (12, 'en', 'Add rows', 'Concates two data sources '),
        (12, 'pt', 'Adicionar linhas', 'Concatena duas fontes de dados'),
        (13, 'en', 'Set intersection', 'Performs set intersection'),
        (13, 'pt', 'Interseção', 'Realiza a interseção entre fontes de dados'),
        (14, 'en', 'Time series', 'Time series'),
        (14, 'pt', 'Séries temporais', 'Séries temporais'),
        (15, 'en', 'Aggregation',
         'Performs aggregation of data grouped by a set of fields'),
        (15, 'pt', 'Agregação',
         'Realiza a agregação de dados agrupados por um conjunto de atributos'),
        (16, 'en', 'Join', 'Joins two data sets using a set of fields (keys)'),
        (16, 'pt', 'Junção (join)',
         'Realiza a junção de fontes de dados usando um conjunto de atributos'
         ' (chaves)'),
        (17, 'en', 'Split',
         'Splits dataset in 2 different data sets using weights'),
        (17, 'pt', 'Dividir',
         'Divide uma fonte de dados em 2 conjutos diferentes, distribuindo '
         'de acordo com pesos'),
        (18, 'en', 'Data reader', 'Reads data from a data set'),
        (18, 'pt', 'Leitor de dados', 'Lê dados de uma fonte de dados'),
        (19, 'en', 'Evaluate model', 'Evaluates a machine learning model'),
        (19, 'pt', 'Avaliar modelo',
         'Avalia um modelo de aprendizado de máquina'),
        (20, 'en', 'Service output',
         'Service output for web service or visualization'),
        (20, 'pt', 'Saída de serviço',
         'Saída para um serviço web ou visualização'),
        (21, 'en', 'Clean missing',
         'Cleans or replaces missing values from fields'),
        (21, 'pt', 'Limpar dados ausentes',
         'Limpa ou substitui dados ausentes'),
        (22, 'en', 'Score model', 'Scores a machine learning model'),
        (22, 'pt', 'Modelo de pontuação', 'Modelo de pontuação'),
        (23, 'en', 'Remove duplicated rows',
         'Remove duplicated rows from data source'),
        (23, 'pt', 'Remover linhas duplicadas',
         'Remove linhas duplicadas de uma fonte de dados'),
        (24, 'en', 'Add Columns',
         'Adds columns from one data source to another'),
        (24, 'pt', 'Adicionar colunas',
         'Adiciona colunas de uma fonte de dados a outra'),
        (25, 'en', 'Comment', 'Comment'),
        (25, 'pt', 'Comentário', 'Comentário'),
        (26, 'en', 'Publish as a visualization',
         'Publishes result as a visualization'),
        (26, 'pt', 'Publicar como visualização',
         'Publica o resultado como uma visualização'),
        (27, 'en', 'Replace value', 'Replaces column value by another'),
        (27, 'pt', 'Substituir valor',
         'Substitui o valor da coluna por outro valor'),
        (28, 'en', 'Sample', 'Generates a sample of data'),
        (28, 'pt', 'Amostrar', 'Gera uma amostra dos dados de entrada'),
        (29, 'en', 'K-Means Clustering',
         'Uses K-Means algorithm for clustering'),
        (29, 'pt', 'Agrupamento K-Means',
         'Usa o algoritmo K-Means para agrupamento'),
        (30, 'en', 'Data writer', 'Writes a new data set'),
        (30, 'pt', 'Escritor de dados', 'Escreve uma nova fonte de dados'),
        (31, 'en', 'Logistic regression', 'Performs logistic regression'),
        (31, 'pt', 'Regressão logística', 'Realiza regressão logística'),
        (32, 'en', 'Sort',
         'Sorts data from data set according to a set of fields and '
         'directions'),
        (32, 'pt', 'Ordenar',
         'Ordena dados de uma fonte de acordo com um conjunto de atributos '
         'e direções'),
        (33, 'en', 'Change attributes',
         'Change metadata information associated to attributes'),
        (33, 'pt', 'Modificar atributos',
         'Altera metadados associados a um ou mais atributos'),
        (34, 'en', 'Broadcast processing data',
         'Distribute small data sets between processing nodes'),
        (34, 'pt', 'Distribuir dados de processamento',
         'Distribui pequenos conjuntos de dados entre os nós de processamento'),
        (35, 'en', 'Table visualization', 'Table visualization'),
        (35, 'pt', 'Visualização em tabela', 'Visualização em tabela'),
        (36, 'en', 'Run application',
         'Executes an application available in the Lemonade catalog'),
        (36, 'pt', 'Executar aplicação',
         'Executa uma aplicação disponível no catálogo do Lemonade'),
        (37, 'en', 'Difference',
         'Returns rows existing in first data set but not in second one'),
        (37, 'pt', 'Diferença',
         'Retorna registros existntes no primeiro conjunto de dados e que '
         'não existem no segundo'),
        (38, 'en', 'Pearson correlation',
         'Calculates the correlation of two attributes of a data source as '
         'a double value'),
        (38, 'pt', 'Correlação de Pearson',
         'Calcula a correlação de Pearson para dois atributos de uma fonte '
         'de dados como valores do tipo double'),
        (39, 'en', 'Save model', 'Saves a model for future use'),
        (39, 'pt', 'Salvar modelo', 'Salva um modelo para uso futuro'),
        (40, 'en', 'Feature indexer',
         'Indexes a feature by encoding a string column as a column containing '
         'indexes for labels (String type) or by encoding a Vector column as a '
         'column containing indexes for these vectors.'),
        (40, 'es', None, None),
        (40, 'pt', 'Indexador feature',
         'Indexa uma feature codificando o texto da coluna como uma coluna '
         'contendo os índices para os rótulos ou codificando uma coluna do tipo'
         ' Vector como uma coluna de índices para esses vetores'),
        (41, 'en', 'Feature assembler',
         ' feature transformer that merges multiple attributes into a vector '
         'attribute'),
        (41, 'es', None, None),
        (41, 'pt', 'Definidor de feature',
         'Transformador de features que mescla atributos em um atributo do '
         'tipo vetor'),
        (42, 'en', 'Apply model', 'Apply a machine learning model to data'),
        (42, 'es', None, None),
        (42, 'pt', 'Aplicar modelo',
         'Aplica um modelo de aprendizado de máquina aos dados'),
        (43, 'en', 'Cross validation', 'Perform cross validation'),
        (43, 'es', None, None),
        (43, 'pt', 'Validação cruzada', 'Realiza a validação cruzada'),
        (44, 'en', 'Random forest classifier', 'Random forest classifier'),
        (44, 'es', None, None),
        (44, 'pt', 'Classificador random forest',
         'Classificador random forest'),
        (45, 'en', 'GBT Classifier',
         'Gradient-Boosted Trees (GBTs) learning algorithm for classification. '
         'It supports binary labels, as well as both continuous and categorical'
         ' features. '),
        (45, 'es', None, None),
        (45, 'pt', 'Classificador GBT',
         'Algoritmo de aprendizado para classificação Gradient-Boosted '
         'Trees (GBTs). Suporta rótulos binários e features contínuas e '
         'categóricas.'),
        (46, 'en', 'Decision tree classifier',
         'Decision tree learning algorithm for classification. It supports both'
         ' binary and multiclass labels, as well as both continuous and '
         'categorical features.'),
        (46, 'es', None, None),
        (46, 'pt', 'Classif. Árv. Decisão',
         'Classificador baseado em árvores de decisão. Suporta tanto rótulos '
         'binários quanto multiclasses e features contínuas e categóricas.'),
        (47, 'en', 'Perceptron Classifier',
         'Classifier trainer based on the Multilayer Perceptron. Each layer '
         'has sigmoid activation function, output layer has softmax. Number of '
         'inputs has to be equal to the size of feature vectors. Number of '),
        (47, 'es', None, None),
        (47, 'pt', ' Classificador Perceptron',
         'Classifier trainer based on the Multilayer Perceptron. Each layer '
         'has sigmoid activation function, output layer has softmax. Number '
         'of inputs has to be equal to the size of feature vectors. '
         'Number of '),
        (48, 'en', 'LDA Clustering', 'LDA Clustering'),
        (48, 'es', None, None),
        (48, 'pt', 'Agrupamento LDA', 'Agrupamento LDA'),
        (49, 'en', 'Tokenizer',
         'Tokenize the input text in a vector of words using a simple tokenizer'
         ' or one based on regular expression.'),
        (49, 'es', None, None),
        (49, 'pt', 'Dividir texto',
         'Divide o texto de entrada em um vetor de palavras usando um separador'
         ' simples ou baseado em expressões regulares.'),
        (50, 'en', 'Remove stop words', 'Remove stop words'),
        (50, 'es', None, None),
        (50, 'pt', 'Remove \'stop words\'', 'Remove stop words'),
        (51, 'en', 'Generate NGrams',
         'A feature transformer that converts the input array of strings into '
         'an array of n-grams. '),
        (51, 'es', None, None),
        (51, 'pt', 'Gerar N-Gramas', 'Converte texto em um vetor de n-gramas'),
        (52, 'en', 'Convert words to vector', 'Convert words to vector'),
        (52, 'es', None, None),
        (
            52, 'pt', 'Converter palavras em vetor',
            'Converter palavras em vetor'),
        (53, 'en', 'Read shapefile', 'Read a shapefile'),
        (53, 'es', None, None),
        (53, 'pt', 'Ler shapefile', 'Lê um arquivo no formato shapefile'),
        (54, 'en', 'Classification Report', 'Classification report'),
        (54, 'es', None, None),
        (54, 'pt', 'Relat. de Classificação', 'Relatório de classificação'),
        (55, 'en', 'Geo Within', 'Locates a point in a shape'),
        (55, 'es', None, None),
        (55, 'pt', 'Geo: localizar ponto', 'Localiza um ponto em um polígono'),
        (56, 'en', 'Gaussian Mix. Clustering', 'Gaussian Mix. Clustering'),
        (56, 'es', None, None),
        (56, 'pt', 'Agrupamento Gaussian Mix.', 'Agrupamento Gaussian Mix.'),
        (57, 'en', 'Data multiplexer',
         'Selects an input according to a set of rules'),
        (57, 'es', None, None),
        (57, 'pt', 'Multiplexador',
         'Seleciona uma entrada de acordo com um conjunto de regras'),
        (58, 'en', 'External input', 'Read data from an external source'),
        (58, 'es', None, None),
        (58, 'pt', 'Entrada externa', 'Lê dados de uma fonte externa'),
        (59, 'en', 'Recommendation Model', 'Recommendation model'),
        (59, 'es', None, None),
        (59, 'pt', 'Modelo de recomendação', 'Modelo de recomendação'),
        (60, 'en', 'ALS Recommender', 'ALS Recommender'),
        (60, 'es', None, None),
        (60, 'pt', 'Recomendador ALS', ' Recomendador ALS'),
        (61, 'en', 'Data reader', 'Data reader'),
        (61, 'es', None, None),
        (61, 'pt', 'Leitor de dados', 'Leitor de dados'),
        (62, 'en', 'Filter', 'Filter'),
        (62, 'es', None, None),
        (62, 'pt', 'Filtro', 'Filtro'),
        (63, 'en', 'Graph', 'Graph'),
        (63, 'es', None, None),
        (63, 'pt', 'Grafo', 'Grafo'),
        (64, 'en', 'Correlation', 'Correlation'),
        (64, 'es', None, None),
        (64, 'pt', 'Correlação', 'Correlação'),
        (65, 'en', 'Word tree', 'Word tree'),
        (65, 'es', None, None),
        (65, 'pt', 'Word tree', 'Word tree'),
        (66, 'en', 'Sentiment analysis', 'Sentiment analysis'),
        (66, 'es', None, None),
        (66, 'pt', 'Análise de sentimentos', 'Análise de sentimentos'),
        (67, 'en', 'Recurrence', 'Recurrence'),
        (67, 'es', None, None),
        (67, 'pt', 'Recorrência', 'Recorrência'),
        (68, 'en', 'Line chart', 'Line chart'),
        (68, 'es', None, None),
        (68, 'pt', 'Gráfico de linha', 'Gráfico de linha'),
        (69, 'en', 'Bar chart', 'Bar chart'),
        (69, 'es', None, None),
        (69, 'pt', 'Gráfico de barras', 'Gráfico de barras'),
        (70, 'en', 'Pie chart', 'Pie chart'),
        (70, 'es', None, None),
        (70, 'pt', 'Gráfico de pizza', 'Gráfico de pizza'),
        (71, 'en', 'Area chart', 'Area chart'),
        (71, 'es', None, None),
        (71, 'pt', 'Gráfico de área', 'Gráfico de área')
    ]
    rows = [dict(list(zip(columns, row))) for row in data]

    op.bulk_insert(tb, rows)


def insert_platform_translation():
    tb = table(
        'platform_translation',
        column('id', Integer),
        column('locale', String),
        column('name', String),
        column('description', String), )

    columns = ('id', 'locale', 'name', 'description')
    data = [
        (1, 'en', 'Spark', 'Apache Spark 2.0 - Execution platform'),
        (1, 'pt', 'Spark', 'Apache Spark 2.0 - Plataforma de execução'),
        (2, 'en', 'Ophidia', 'Ophidia'),
        (2, 'pt', 'Ophidia', 'Ophidia'),
        (3, 'en', 'COMPSs', 'COMPSs'),
        (3, 'pt', 'COMPSs', 'COMPSs'),
    ]
    rows = [dict(list(zip(columns, row))) for row in data]
    op.bulk_insert(tb, rows)


def downgrade():
    try:
        op.execute(text('START TRANSACTION'))
        op.execute(text(
            'DELETE FROM operation_form_field_translation '
            'WHERE id BETWEEN 1 AND 192'))

        op.execute(text(
            'DELETE FROM operation_form_translation '
            'WHERE id BETWEEN 1 AND 86'))

        op.execute(text(
            'DELETE FROM operation_operation_form '
            'WHERE operation_id BETWEEN 1 AND 96'))

        op.execute(text(
            'DELETE FROM operation_platform '
            'WHERE operation_id BETWEEN 1 AND 96'))

        op.execute(text('DELETE FROM platform_translation '
                        'WHERE id BETWEEN 1 AND 3'))
        op.execute(text('DELETE FROM platform WHERE id BETWEEN 1 AND 3'))

        op.execute(text('DELETE FROM operation_translation '
                        'WHERE id BETWEEN 1 AND 96'))
    except:
        op.execute(text('ROLLBACK'))
        raise